Fix a build error in the latest yocto build
Updated compiler has more strict rule on duplicate template definition
so this commit fixes the error.

Tested: Below error was removed by this change:
| In file included from ../git/drive.cpp:29:
| ../git/protocol/mi_rsp.hpp:113:1: error: deduction guide 'template<class T> nvmemi::protocol::ManagementInterfaceResponse(T&)-> nvmemi::protocol::ManagementInterfaceResponse<unsigned char*>' redeclared
|   113 | ManagementInterfaceResponse(T&) -> ManagementInterfaceResponse<uint8_t*>;
|       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
| ../git/protocol/mi_rsp.hpp:111:1: note: 'template<class T> nvmemi::protocol::ManagementInterfaceResponse(T&)-> nvmemi::protocol::ManagementInterfaceResponse<unsigned char*>' previously declared here
|   111 | ManagementInterfaceResponse(T&) -> ManagementInterfaceResponse<uint8_t*>;
|       | ^~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Jae Hyun Yoo <jae.hyun.yoo@intel.com>
Change-Id: I17c89c7ed0272e0edf3f904041db51789879aca6